shell = "zsh"

[plugins]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completion]
github = "zsh-users/zsh-completions"

[plugins.zsh-syntax-hilighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-abbr]
github = "olets/zsh-abbr"